[
    "task(vw1rwf43ybudja4)",
    "blonde angelic woman",
    "",
    [],
    20,
    "Euler a",
    false,
    false,
    2,
    3,
    7,
    -1,
    -1,
    0,
    0,
    0,
    false,
    512,
    512,
    false,
    0.7,
    2,
    "Latent",
    0,
    0,
    0,
    "Use same sampler",
    "",
    "",
    [],
    "None",
    false,
    false,
    "positive",
    "comma",
    0,
    false,
    false,
    "",
    "Seed",
    "",
    [],
    "Nothing",
    "",
    [],
    "Nothing",
    "",
    [],
    true,
    false,
    false,
    false,
    0,
    [
        {
            "name": "/home/wsutt/sd/stable-diffusion-webui/outputs/txt2img-images/2023-08-10/00001-1125342989.png",
            "data": "http://34.172.214.221:7862/file=/home/wsutt/sd/stable-diffusion-webui/outputs/txt2img-images/2023-08-10/00001-1125342989.png",
            "is_file": true
        }
    ],
    "{\"prompt\": \"blonde angelic woman\", \"all_prompts\": [\"blonde angelic woman\"], \"negative_prompt\": \"\", \"all_negative_prompts\": [\"\"], \"seed\": 1125342989, \"all_seeds\": [1125342989], \"subseed\": 4277471480, \"all_subseeds\": [4277471480], \"subseed_strength\": 0, \"width\": 512, \"height\": 512, \"sampler_name\": \"Euler a\", \"cfg_scale\": 7, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"15012c538f\", \"seed_resize_from_w\": 0, \"seed_resize_from_h\": 0, \"denoising_strength\": null, \"extra_generation_params\": {}, \"index_of_first_image\": 0, \"infotexts\": [\"blonde angelic woman\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1125342989, Size: 512x512, Model hash: 15012c538f, Model: model, Version: v1.5.1\"], \"styles\": [], \"job_timestamp\": \"20230810190214\", \"clip_skip\": 1, \"is_using_inpainting_conditioning\": false}",
    "<p>blonde angelic woman<br>\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1125342989, Size: 512x512, Model hash: 15012c538f, Model: model, Version: v1.5.1</p>",
    "<p class='comments'></p><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>4.5 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>3.09 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>3.60 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>4.8/14.5615 GB</span> (32.7%)</p></div>"
]